#!/bin/sh

DESC="IoT Virtual Devices"
NAME=iot_virtual_devices
PIDFILE=/var/run/$NAME.pid
RUN_AS=root
COMMAND=/usr/bin/java
CMD_PARAMS="-jar /usr/share/iot_virtual_devices/iot_virtual_devices.jar /usr/share/iot_virtual_devices/config.properties"
CONFIG_PATH=/usr/share/iot_virtual_devices/

d_start() {
    cd $CONFIG_PATH
    #start-stop-daemon --start --make-pidfile --pidfile $PIDFILE --exec $COMMAND -- $CMD_PARAMS
    start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --chuid $RUN_AS --exec $COMMAND -- $CMD_PARAMS

    e=$?
    if [ $e -eq 1 ]; then
       echo "already running"
       return
    fi

    if [ $e -eq 255 ]; then
       echo "couldn't start :("
       exit 1
    fi

}

d_stop() {
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    if [ -e $PIDFILE ]
        then rm $PIDFILE
    fi
}

case $1 in
    start)
    echo -n "Starting $DESC: $NAME"
    d_start
    echo "."
    ;;
    stop)
    echo -n "Stopping $DESC: $NAME"
    d_stop
    echo "."
    ;;
    restart)
    echo -n "Restarting $DESC: $NAME"
    d_stop
    sleep 1
    d_start
    echo "."
    ;;
    *)
    echo "usage: $NAME {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
